openapi: 3.0.3
info:
  version: 1.66.0
  title: FusionAuth Api Key Report API
  description: This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
  license:
    name: Apache2
servers:
- url: http://localhost:9011
- url: https://sandbox.fusionauth.io
security:
- ApiKeyAuth: []
tags:
- name: Report
paths:
  /api/report/daily-active-user:
    get:
      description: Retrieves the daily active user report between the two instants. If you specify an application Id, it will only return the daily active counts for that application.
      operationId: retrieveDailyActiveReportWithId
      parameters:
      - name: applicationId
        in: query
        schema:
          type: string
        description: The application Id.
      - name: start
        in: query
        schema:
          type: string
        description: The start instant as UTC milliseconds since Epoch.
      - name: end
        in: query
        schema:
          type: string
        description: The end instant as UTC milliseconds since Epoch.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DailyActiveUserReportResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
      tags:
      - Report
  /api/report/login:
    get:
      description: Retrieves the login report between the two instants for a particular user by login Id, using specific loginIdTypes. If you specify an application id, it will only return the login counts for that application. OR Retrieves the login report between the two instants for a particular user by login Id. If you specify an application Id, it will only return the login counts for that application. OR Retrieves the login report between the two instants for a particular user by Id. If you specify an application Id, it will only return the login counts for that application. OR Retrieves the login report between the two instants. If you specify an application Id, it will only return the login counts for that application.
      operationId: retrieveReportLogin
      parameters:
      - name: applicationId
        in: query
        schema:
          type: string
        description: The application id.
      - name: loginId
        in: query
        schema:
          type: string
        description: The userId id.
      - name: start
        in: query
        schema:
          type: string
        description: The start instant as UTC milliseconds since Epoch.
      - name: end
        in: query
        schema:
          type: string
        description: The end instant as UTC milliseconds since Epoch.
      - name: loginIdTypes
        in: query
        schema:
          type: array
          items:
            type: string
        description: The identity types that FusionAuth will compare the loginId to.
      - name: userId
        in: query
        schema:
          type: string
        description: The userId Id.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginReportResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
      tags:
      - Report
  /api/report/monthly-active-user:
    get:
      description: Retrieves the monthly active user report between the two instants. If you specify an application Id, it will only return the monthly active counts for that application.
      operationId: retrieveMonthlyActiveReportWithId
      parameters:
      - name: applicationId
        in: query
        schema:
          type: string
        description: The application Id.
      - name: start
        in: query
        schema:
          type: string
        description: The start instant as UTC milliseconds since Epoch.
      - name: end
        in: query
        schema:
          type: string
        description: The end instant as UTC milliseconds since Epoch.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonthlyActiveUserReportResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
      tags:
      - Report
  /api/report/registration:
    get:
      description: Retrieves the registration report between the two instants. If you specify an application Id, it will only return the registration counts for that application.
      operationId: retrieveRegistrationReportWithId
      parameters:
      - name: applicationId
        in: query
        schema:
          type: string
        description: The application Id.
      - name: start
        in: query
        schema:
          type: string
        description: The start instant as UTC milliseconds since Epoch.
      - name: end
        in: query
        schema:
          type: string
        description: The end instant as UTC milliseconds since Epoch.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationReportResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
      tags:
      - Report
  /api/report/totals:
    get:
      description: Retrieves the totals report. This allows excluding applicationTotals from the report. An empty list will include the applicationTotals.
      operationId: retrieveTotalReportWithExcludesWithId
      parameters:
      - name: excludes
        in: query
        schema:
          type: array
          items:
            type: string
        description: List of fields to exclude in the response. Currently only allows applicationTotals.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TotalsReportResponse'
        default:
          description: Error
      tags:
      - Report
components:
  schemas:
    Errors:
      description: Standard error domain object that can also be used as the response from an API call.
      type: object
      properties:
        fieldErrors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        generalErrors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    Totals:
      type: object
      properties:
        logins:
          type: integer
          format: int64
        registrations:
          type: integer
          format: int64
        totalRegistrations:
          type: integer
          format: int64
    Error:
      description: Defines an error.
      type: object
      properties:
        code:
          type: string
        data:
          type: object
          additionalProperties:
            type: object
        message:
          type: string
    DailyActiveUserReportResponse:
      description: Response for the daily active user report.
      type: object
      properties:
        dailyActiveUsers:
          type: array
          items:
            $ref: '#/components/schemas/Count'
        total:
          type: integer
          format: int64
    TotalsReportResponse:
      description: The response from the total report. This report stores the total numbers for each application.
      type: object
      properties:
        applicationTotals:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Totals'
        globalRegistrations:
          type: integer
          format: int64
        totalGlobalRegistrations:
          type: integer
          format: int64
    RegistrationReportResponse:
      description: Response for the registration report.
      type: object
      properties:
        hourlyCounts:
          type: array
          items:
            $ref: '#/components/schemas/Count'
        total:
          type: integer
          format: int64
    LoginReportResponse:
      description: Response for the login report.
      type: object
      properties:
        hourlyCounts:
          type: array
          items:
            $ref: '#/components/schemas/Count'
        total:
          type: integer
          format: int64
    Count:
      description: ''
      type: object
      properties:
        count:
          type: integer
        interval:
          type: integer
    MonthlyActiveUserReportResponse:
      description: Response for the daily active user report.
      type: object
      properties:
        monthlyActiveUsers:
          type: array
          items:
            $ref: '#/components/schemas/Count'
        total:
          type: integer
          format: int64
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
